package trabajopractico3ejercicio1;

import java.util.Arrays;

import javax.swing.JOptionPane;

public class TrabajoPracticoEjercicio1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TrabajoPracticoEjercicio1.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public TrabajoPracticoEjercicio1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EntradaUsuario = new javax.swing.JTextField();
        EntradaPass = new javax.swing.JPasswordField();
        LabelContraseña = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        BotonVerificar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BtnOcultar = new javax.swing.JButton();
        BtnVer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese las credenciales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(EntradaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 260, -1));
        jPanel1.add(EntradaPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 260, -1));

        LabelContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelContraseña.setForeground(new java.awt.Color(0, 0, 0));
        LabelContraseña.setText("Contraseña:");
        jPanel1.add(LabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        LabelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(0, 0, 0));
        LabelUsuario.setText("Usuario:");
        jPanel1.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        BotonVerificar.setBackground(new java.awt.Color(255, 255, 255));
        BotonVerificar.setForeground(new java.awt.Color(0, 0, 0));
        BotonVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cliente-windows-48.png"))); // NOI18N
        BotonVerificar.setText("Verificar");
        BotonVerificar.addActionListener(this::BotonVerificarActionPerformed);
        jPanel1.add(BotonVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 200, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 410, 230));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnOcultar.setBackground(new java.awt.Color(255, 255, 255));
        BtnOcultar.setForeground(new java.awt.Color(0, 0, 0));
        BtnOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons7-ocultar-contraseña-50.png"))); // NOI18N
        BtnOcultar.setText("OCULTAR");
        BtnOcultar.addActionListener(this::BtnOcultarActionPerformed);
        jPanel2.add(BtnOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        BtnVer.setBackground(new java.awt.Color(255, 255, 255));
        BtnVer.setForeground(new java.awt.Color(0, 0, 0));
        BtnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons7-mostrar-contraseña-50.png"))); // NOI18N
        BtnVer.setText("VER");
        BtnVer.addActionListener(this::BtnVerActionPerformed);
        jPanel2.add(BtnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 510, 100));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Inicio de sesion");
        jPanel3.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 220, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerificarActionPerformed
        String usuario = EntradaUsuario.getText().trim();
        final char[] PassCorrecta = {'1', '2', '3', '4', '5', '6', '7', '8'};
        char password[] = EntradaPass.getPassword();
        if (usuario.equals("alumno@ulp.edu.ar") && Arrays.equals(password,PassCorrecta)){
            JOptionPane.showMessageDialog(this,"Bienvenido al sistema");
        }else JOptionPane.showMessageDialog(this,"Usuario y/o contraseña incorrecta");
    }//GEN-LAST:event_BotonVerificarActionPerformed

    private void BtnOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOcultarActionPerformed
        EntradaPass.setEchoChar('*');
    }//GEN-LAST:event_BtnOcultarActionPerformed

    private void BtnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerActionPerformed
        EntradaPass.setEchoChar((char)0);
    }//GEN-LAST:event_BtnVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TrabajoPracticoEjercicio1().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonVerificar;
    private javax.swing.JButton BtnOcultar;
    private javax.swing.JButton BtnVer;
    private javax.swing.JPasswordField EntradaPass;
    private javax.swing.JTextField EntradaUsuario;
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
